// ATTENTION!
// THIS FILE IS AUTO GENERATED BY CODE GENERATOR.
// DONT TRY TO CHANGE IT MANUALY!
using UnityEngine;

public static class ResDB {
	static GameStateChangeEvent GameStateObjCache = null; // object cache
	public static GameStateChangeEvent GameStateAsset() {
		if (GameStateObjCache==null)
			GameStateObjCache = Resources.Load<GameStateChangeEvent>("GameState");
		return GameStateObjCache;
	} // end method GameStateAsset
	
	static IntValue MarkedObjectsLevelCountObjCache = null; // object cache
	public static IntValue MarkedObjectsLevelCountAsset() {
		if (MarkedObjectsLevelCountObjCache==null)
			MarkedObjectsLevelCountObjCache = Resources.Load<IntValue>("MarkedObjectsLevelCount");
		return MarkedObjectsLevelCountObjCache;
	} // end method MarkedObjectsLevelCountAsset
	
	static Vector3Value PlayerPositionObjCache = null; // object cache
	public static Vector3Value PlayerPositionAsset() {
		if (PlayerPositionObjCache==null)
			PlayerPositionObjCache = Resources.Load<Vector3Value>("PlayerPosition");
		return PlayerPositionObjCache;
	} // end method PlayerPositionAsset
	
	static IntValue PowerUpObjCache = null; // object cache
	public static IntValue PowerUpAsset() {
		if (PowerUpObjCache==null)
			PowerUpObjCache = Resources.Load<IntValue>("PowerUp");
		return PowerUpObjCache;
	} // end method PowerUpAsset
	
	static FloatValue PowerUpTimeObjCache = null; // object cache
	public static FloatValue PowerUpTimeAsset() {
		if (PowerUpTimeObjCache==null)
			PowerUpTimeObjCache = Resources.Load<FloatValue>("PowerUpTime");
		return PowerUpTimeObjCache;
	} // end method PowerUpTimeAsset
	
	static IntValue TotalLevelObjectsCountObjCache = null; // object cache
	public static IntValue TotalLevelObjectsCountAsset() {
		if (TotalLevelObjectsCountObjCache==null)
			TotalLevelObjectsCountObjCache = Resources.Load<IntValue>("TotalLevelObjectsCount");
		return TotalLevelObjectsCountObjCache;
	} // end method TotalLevelObjectsCountAsset
	

public static class Configs {
		static LevelConfig TestLevelObjCache = null; // object cache
		public static LevelConfig TestLevelAsset() {
			if (TestLevelObjCache==null)
				TestLevelObjCache = Resources.Load<LevelConfig>("Configs/TestLevel");
			return TestLevelObjCache;
		} // end method TestLevelAsset
		
		static LevelConfig TestLevel2ObjCache = null; // object cache
		public static LevelConfig TestLevel2Asset() {
			if (TestLevel2ObjCache==null)
				TestLevel2ObjCache = Resources.Load<LevelConfig>("Configs/TestLevel2");
			return TestLevel2ObjCache;
		} // end method TestLevel2Asset
		
} // end of class Configs

public static class Managers {
		static DebrisPool DebrisPoolObjCache = null; // object cache
		public static DebrisPool DebrisPoolAsset() {
			if (DebrisPoolObjCache==null)
				DebrisPoolObjCache = Resources.Load<DebrisPool>("Managers/DebrisPool");
			return DebrisPoolObjCache;
		} // end method DebrisPoolAsset
		
} // end of class Managers
} // end of class ResDB
